# Generated by Django 4.1.7 on 2023-05-30 10:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0013_remove_post_likes_remove_post_reply_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes_post',
            field=models.ManyToManyField(blank=True, related_name='postcomment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='save_posts',
            field=models.ManyToManyField(blank=True, related_name='saveposts', to=settings.AUTH_USER_MODEL),
        ),
    ]
