# Generated by Django 4.1.7 on 2023-05-30 10:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0014_post_likes_post_post_save_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes_post',
            field=models.ManyToManyField(blank=True, related_name='post_comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='save_posts',
            field=models.ManyToManyField(blank=True, related_name='save_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
